Move Operator Hub out of experimental mode
openshift/odo pull request #3883
Opened 2020-09-02 11:12 UTC by dharmit

**What type of PR is this?**
/kind feature
/kind code-refactoring

**What does does this PR do / why we need it**:
It moves Operator Hub integration out of experimental mode. We need it for v2.

**Which issue(s) this PR fixes**:

Fixes #3595 

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
* Tests should pass.
* If Operators are supported by the cluster (4.x), we ignore service catalog altogether.
* If user's working with 3.x cluster, odo should support Service Catalog (if enabled by the user).

2020-09-02 13:37 UTC, dharmit commented
Looks like Travis is failing while linking component to component on 3.x. I didn't factor that while working on this PR. Will take a look at it and update the PR.

2020-09-08 18:33 UTC, cdrage requested changes
This PR looks great! Super minor changes with regards to code that has been commented out as well as comments that should be fixed.

2020-09-08 18:33 UTC, cdrage commented on pkg/component/component.go
> +// GetDevfileComponentLinkedSecretNames
Need to add more description here / comments, sorry! :)

2020-09-08 18:33 UTC, cdrage commented on pkg/kclient/deployments.go
> +		return nil, errors.Wrapf(err, "unable to get Deployments for the selector: %v", selector)
remove capitalization from `Deployment`

2020-09-08 18:33 UTC, cdrage commented on pkg/kclient/deployments.go
> +		return nil, fmt.Errorf("no Deployment was found for the selector: %v", selector)
remove capitalization from `Deployment`

2020-09-08 18:33 UTC, cdrage commented on pkg/kclient/deployments.go
> +		return nil, fmt.Errorf("multiple Deployments exist for the selector: %v. Only one must be present", selector)
remove capitalization from `Deployment`

2020-09-08 18:33 UTC, cdrage commented on pkg/kclient/deployments.go
> +	// }
Shouldn't we remove this?

2020-09-08 18:33 UTC, cdrage commented on pkg/kclient/deployments.go
> +// this function will look up the appropriate DC, and execute the specified patch
Comments should always start with the function name `patchDeploymentOfComponent` or else `gofmt` will complain / get mad

2020-09-08 18:33 UTC, cdrage commented on pkg/kclient/deployments.go
> +		return errors.Wrapf(err, "Unable to locate Deployment for component %s of application %s", componentName, applicationName)
remove capitalization from error

2020-09-08 18:33 UTC, cdrage commented on pkg/kclient/deployments.go
> +			return errors.Wrap(err, "Unable to create a patch for the Deployment")
remove capitalization from error

2020-09-08 18:33 UTC, cdrage commented on pkg/kclient/deployments.go
> +			return errors.Wrapf(err, "Deployment not patched %s", deployment.Name)
remove capitalization from error

2020-09-08 18:33 UTC, cdrage commented on pkg/odo/cli/component/common_link.go
> +		// }
Remove above?

2020-09-15 04:50 UTC, dharmit commented
Closing since take care by #3938.

/close

2020-09-15 04:50 UTC, closed without merging