Adds a document regarding the usage of storage commands.
openshift/odo pull request #3936
Opened 2020-09-11 08:00 UTC by mik-dass

**What type of PR is this?**

/kind documentation

**What does does this PR do / why we need it**:

It adds a document about the usage of storage commands.

**Which issue(s) this PR fixes**:

Fixes #3761

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [X] Documentation 

- [X] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

Check if the document is correct, clear and easy to understand.

2020-09-11 08:57 UTC, mik-dass commented
```
level=error msg="Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get https://api.ci-op-i335nzk0-2f74e.origin-ci-int-aws.dev.rhcloud.com:6443/apis/config.openshift.io/v1/clusteroperators: dial tcp 3.219.116.198:6443: connect: connection refused"
```

2020-09-11 08:58 UTC, mik-dass commented
```
level=error msg="Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get https://api.ci-op-i335nzk0-2f74e.origin-ci-int-aws.dev.rhcloud.com:6443/apis/config.openshift.io/v1/clusteroperators: dial tcp 3.219.116.198:6443: connect: connection refused"
```
/retest

2020-09-11 13:23 UTC, cdrage commented
Hey @mik-dass unfortunately the document isn't the same format as other documentation such as: https://github.com/openshift/odo/blob/b0cc651f8f14ec7e17ef38d33b0fe234e637b85b/docs/public/deploying-a-devfile-using-odo.adoc

There are certain (unwritten) requirements that we follow from the OpenShift docs team. @boczkowska unsure if Yana has an official link to it.

For example, for each command, we need to have `$` in front of the command, and for anything that's ran by root, it has to have `#`

2020-09-11 13:27 UTC, cdrage requested changes
Have to write this in adoc!

2020-09-11 13:27 UTC, cdrage commented on docs/public/using-storage.adoc
> +```
Have to use: 

```
. This is an example heading:
+
[source,sh]
----
```

2020-09-14 12:32 UTC, mik-dass commented
@cdrage Fixed

2020-09-16 11:18 UTC, girishramnani commented
I am thinking about `you can a storage` - I mean shouldn’t it be “storage volume”. And also should we explain what that means? Because a new user would naturally ask that “without “storage” I don’t have any storage capacity in my component?”
Explaining that adding a storage volumes means that data in that directory would persist across rebuilds seems like a good idea. Just a suggestion.

2020-09-30 07:03 UTC, mik-dass commented
@girishramnani Fixed.

2020-09-30 08:52 UTC, kadel commented
This is good start.
/lgtm
/approve

2020-09-30 08:52 UTC, kadel commented
/override ci/prow/v4.5-integration-e2e 
this is just docs, we don't need to wait for tests

2020-09-30 08:54 UTC, merged