check if devfile exist in the context folder instead of working direc…
openshift/odo pull request #4149
Opened 2020-10-24 20:55 UTC by girishramnani

…tory

**What type of PR is this?**
/kind bug

**What does does this PR do / why we need it**:
Currently we were deciding the type of context ( devfile or s2i ) based on presence of devfile in the working directory which is a problem when user provides `--context`.  For e.g.
- `odo describe --context <s2i-component-dir>` <- this from a directory that has devfile directory would fail as it would initialise a `DevfileContext` that looks for `env.yaml`. 

**Which issue(s) this PR fixes**:

Fixes https://github.com/openshift/odo/issues/3902

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [X] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

- create a nodejs s2i component - `nodejs2i`
- create a nodejs devfile component - `nodejsdevfile` along side the s2i component so that both sit in the same dir
- now go to the `nodejsdevfile` component dir and run `odo describe --context ../nodejs2i`

Before this PR it should fail with
```
 ✗  The current directory does not represent an odo component. Use 'odo create' to create component here or switch to directory with a component
```

Now it should show the description.

2020-10-26 15:41 UTC, kadel commented
/approve

Wouldn't this be a good candidate for an integration test?

2020-10-27 12:14 UTC, girishramnani commented
> /approve
> 
> Wouldn't this be a good candidate for an integration test?

agreed adding an integration test

2020-11-02 20:27 UTC, girishramnani commented
/retest

2020-11-04 12:34 UTC, dharmit requested changes
One nit. Looks good otherwise.

2020-11-04 12:34 UTC, dharmit commented on tests/integration/devfile/cmd_devfile_create_test.go
> +		AfterEach(func() {
Nit: should this be `JustAfterEach`? Also, I think, we have a common `BeforeEach` & `AfterEach`.

2020-11-04 12:38 UTC, dharmit approved these changes
/lgtm

2020-11-05 11:15 UTC, merged