Modifies odo create for devfile components to not require a cluster access.
openshift/odo pull request #4436
Opened 2021-02-16 09:28 UTC by mik-dass

Signed-off-by: mik-dass <mrinald7@gmail.com>

**What type of PR is this?**

/kind bug

**What does does this PR do / why we need it**:

It also modifies odo push to fill the project name in env.yaml if no project is not found in it.

**Which issue(s) this PR fixes**:

Fixes #3811 

**PR acceptance criteria**:

- [ ] Unit test 

- [X] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

- `odo create` should work without a cluster.
- `odo create --project <name>` should fill the project name in env.yaml during creation.
- `odo push` should fill the project name in the env.yaml if none was provided during creation.

2021-02-17 12:47 UTC, dharmit commented
I'm seeing `Validation` showing up twice when I try to create `--s2i` component:
```sh
$ odo create --s2i nodejs
Validation   <---------
Validation   <---------
 ✓  Validating component [6ms]

Please use `odo push` command to create the component with source deployed
```

2021-02-17 13:13 UTC, dharmit commented
This one probably deserves a separate issue:
```sh
$ odo logout

$ odo create nodejs node --now
Devfile Object Validation
 ✓  Checking devfile existence [13129ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [21051ns]
Validation
 ✓  Validating if devfile name is correct [33281ns]
 ✗  failed to push changes: Failed to start component with name node. Error: Failed to create the component: unable to determine if component node exists: deployments.apps "node" is forbidden: User "system:anonymous" cannot get resource "deployments" in API group "apps" in the namespace "myproject"
```
Couple of things related to the error message being printed upon failure:
* Use quotes for name of the component. This could be easily done by using `%q` in code in place of `%s`:
    ```
    failed to push changes: Failed to start component with name "node". Error: Failed to create the component: unable to determine if component "node" exists: deployments.apps "node" is forbidden: User "system:anonymous" cannot get resource "deployments" in API group "apps" in the namespace "myproject"
    ```
    
* More importantly, the error message should be more clear to indicate that odo is not connected to any cluster.

2021-02-17 13:15 UTC, mik-dass commented
> I'm seeing Validation showing up twice when I try to create --s2i component:

There is a separate issue for that https://github.com/openshift/odo/issues/4422

> This one probably deserves a separate issue:

Yes, it should be a different issue.

2021-02-17 13:19 UTC, dharmit commented
One last observation related to functionality. I created the component with `--project` flag. I know that the project doesn't exist on the cluster I'm going to login to. Should odo create a project upon `odo push` in such scenario? Definitely a separate issue, IMO.
```sh
$ odo create python --project randomproject
Devfile Object Validation
 ✓  Checking devfile existence [168192ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [48038ns]
Validation
 ✓  Validating if devfile name is correct [25674ns]

Please use `odo push` command to create the component with source deployed

$ odo login https://api.crc.testing:6443 -u developer -p developer 
Connecting to the OpenShift cluster

Login successful.

You have one project on this server: "myproject"

Using project "myproject".

$ odo push
 ✗  Failed to start component with name python. Error: Failed to create the component: unable to determine if component python exists: deployments.apps "python" is forbidden: User "developer" cannot get resource "deployments" in API group "apps" in the namespace "randomproject"
```

2021-02-17 13:28 UTC, dharmit commented
Sorry, I was lying about one last functionality observation in my previous comment. Here goes one more. 

I'm connected to the cluster. The scenario is when user is by default working on `default` project on OpenShift which is the case when one has spun up a fresh CRC cluster.
```sh
$ odo project get
The current project is: default

$ odo create nodejs                        
Devfile Object Validation
 ✓  Checking devfile existence [16336ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [26803ns]
Validation
 ✓  Validating if devfile name is correct [20604ns]

Please use `odo push` command to create the component with source deployed

$ cat .odo/env/env.yaml
ComponentSettings:
  Name: nodejs
  AppName: app

$ odo push
 ✗  Failed to start component with name nodejs. Error: Failed to create the component: unable to determine if component nodejs exists: deployments.apps "nodejs" is forbidden: User "developer" cannot get resource "deployments" in API group "apps" in the namespace "default"

# now the env.yaml has an entry for "Project"
$ cat .odo/env/env.yaml
ComponentSettings:
  Name: nodejs
  Project: default
  AppName: app
```
I don't know the answer to what exactly should be done in this case. But there should definitely be better error handling when `odo push` is done in such a scenario. Making sure that `Project: default` doesn't get populated in `env.yaml` might be a nice to have as well since we want to prevent users from trying to push stuff to `default` namespace on OpenShift.

2021-02-17 14:25 UTC, kadel commented
> One last observation related to functionality. I created the component with `--project` flag. I know that the project doesn't exist on the cluster I'm going to login to. Should odo create a project upon `odo push` in such scenario? Definitely a separate issue, IMO.

We can decide on project creation later. But the error that is currently thrown in this situation is quite misleading. 

`odo push` should check if project/namespace exist. If not it should print nice error. Something like:
```
The project that you are trying to push to doesn't exist. Please create project first (odo project create myproject)
```

2021-02-17 14:28 UTC, kadel commented
> I'm connected to the cluster. The scenario is when user is by default working on `default` project on OpenShift which is the case when one has spun up a fresh CRC cluster.

In this case  `odo push` should error out. We had a check in `odo create` that prints an error if the user tries to create component in `default` project on OpeShift. We need to move this check to `odo push`

2021-02-23 09:17 UTC, mik-dass commented
@kadel @dharmit Fixed

2021-02-24 12:24 UTC, dharmit requested changes
Confused by the integration tests. IIUC, we've added two tests - one for OpenShift, one for k8s. And we're skipping both if the environment is k8s. Is this by design? Shouldn't the test written for k8s be run when the environment is k8s?

2021-02-24 14:24 UTC, mik-dass commented
> Confused by the integration tests. IIUC, we've added two tests - one for OpenShift, one for k8s. And we're skipping both if the environment is k8s.

We are not skipping both if the environment is k8s. One of the condition is
```
if os.Getenv("KUBERNETES") == "true" 
```
and the other one is the opposite
```
if os.Getenv("KUBERNETES") != "true"
```

2021-02-25 05:20 UTC, dharmit commented
> ```
> if os.Getenv("KUBERNETES") != "true"
> ```

:man_facepalming: 

/lgtm

2021-02-25 11:06 UTC, merged