fix json in describe component
openshift/odo pull request #4506
Opened 2021-03-11 14:03 UTC by kadel

**What type of PR is this?**

/kind bug

**What does does this PR do / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/openshift/odo/issues/4474

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

run `odo catalog describe component nodejs -o json` 
the output should be a valid json struct (array)

2021-03-11 15:04 UTC, kadel commented
/retest
timeouts

2021-03-12 09:57 UTC, prietyc123 commented
@kadel Can we validate this scenario by adding tests with similar behaviour?

2021-03-12 09:58 UTC, prietyc123 requested changes
https://github.com/openshift/odo/pull/4506#issuecomment-797377611

2021-03-15 16:33 UTC, kadel commented
> @kadel Can we validate this scenario by adding tests with similar behaviour?

done

2021-03-16 06:19 UTC, mik-dass commented on pkg/odo/cli/catalog/describe/component.go
> +// DevfileComponentDescription represents the JSON output of Devfile compoent description
`component`

2021-03-16 09:42 UTC, kadel commented on pkg/odo/cli/catalog/describe/component.go
> +// DevfileComponentDescription represents the JSON output of Devfile compoent description
fixed

2021-03-16 11:57 UTC, mik-dass approved these changes
/lgtm

2021-03-16 15:10 UTC, merged