Get SB secret name from SB
openshift/odo pull request #4554
Opened 2021-03-25 16:08 UTC by kadel

**What type of PR is this?**

/kind bug

**What does does this PR do / why we need it**:

Currently, odo assumes that  Secret created by SBO has the same name as ServiceBinding.
This is no longer valid. SBO Secrets have some kind of has as a suffix. 
This PR makes sure that odo detect the correct Secret name from SB definition. 

**Which issue(s) this PR fixes**:

Fixes #?

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

2021-03-26 09:35 UTC, dharmit requested changes

2021-03-26 09:35 UTC, dharmit commented on pkg/odo/cli/component/common_link.go
> +			}
I'm getting build error due to missing `,` here.

2021-03-26 09:39 UTC, dharmit commented on pkg/odo/cli/component/common_link.go
> +			Ref: ref,
If I add `,` as [pointed here](https://github.com/openshift/odo/pull/4554/files#r602136902) I get below build error:
```
pkg/odo/cli/component/common_link.go:142:4: unknown field 'Ref' in struct literal of type "github.com/redhat-developer/service-binding-operator/pkg/apis/operators/v1alpha1".Application
```

2021-03-26 09:42 UTC, dharmit commented on pkg/odo/cli/component/common_link.go
> +			Ref: ref,
If I replace `Ref` with `LocalObjectReference` (I used `Ctrl+Space` to see what the IDE suggests), it complains that `ref` is undefined:
```sh
pkg/odo/cli/component/common_link.go:142:26: undefined: ref
```

2021-03-26 09:43 UTC, dharmit commented
@kadel wondering if you were able to test this successfully on local setup because on my end, when I checkout this PR, I am not able to build odo binary. 😕

2021-03-26 10:15 UTC, kadel commented
> @kadel wondering if you were able to test this successfully on local setup because on my end, when I checkout this PR, I am not able to build odo binary. 😕

I picked this commit from a branch with other changes, I guess `git cherry-pick` had some problems merging it.

2021-03-26 10:19 UTC, dharmit commented
> I picked this commit from a branch with other changes, I guess `git cherry-pick` had some problems merging it.

OK. I was thinking maybe you used Notepad since you recently moved to Windows. 🤔

2021-03-26 16:16 UTC, wtrocki commented
I'm not part of the team but why we need to detect SBO secret? 
My understanding is that for ODO work should be finished once CR is created and `status.conditions.ready==="True"`

2021-03-26 18:10 UTC, kadel commented
> I'm not part of the team but why we need to detect SBO secret?
> My understanding is that for ODO work should be finished once CR is created and `status.conditions.ready==="True"`

The reason is this https://github.com/openshift/odo/issues/4553

Currently, odo can't handle if someone else modifies Deployment :/ once you run `odo push` it will override all changes that were not made by odo.
I bad design I know :( , but at the time when this was written there was no other way.

2021-03-26 18:20 UTC, wtrocki commented
@kadel would it be possible to jump on call some day for 20 minutes max?

2021-03-29 09:39 UTC, kadel commented
> I think supporting file based bindings might have been little premature step that was triggered by some enthusiast who did not know ODO internals :). In SBO 0.7.0 we will get option to run it as SDK - which will mean that ODO could apply bindings locally and avoid problem with overriding resources. When doing work to support from file binding I actually learned a lot about ODO internals and current state. Changing push to patch mode is risky business IMHO and should not be done only for supporting sbo

I did some experiments on Friday and it looks like moving to the patch might not be that risky, but need to do more testing and run a full test suite against the changes, so I'm not going to open PR yet.

My experimental branch with patch and vendored  SBO 0.6.0 and OpenShift libs updated to 4.7 is here https://github.com/kadel/odo/tree/ssa

2021-03-29 11:37 UTC, wtrocki commented
@kadel Amazing work!

2021-03-30 09:31 UTC, kadel commented
This PR is ready. This is not an ideal solution, but It fixes one of the immediate problems that we have right now.

I'm working on proper fix in https://github.com/kadel/odo/tree/ssa but this is a larger chance that will require more tests and time.

2021-03-30 09:44 UTC, dharmit commented
> This PR is ready. This is not an ideal solution, but It fixes one of the immediate problems that we have right now.

`odo link` functionality looks OK. Checking the code.

2021-03-30 09:55 UTC, dharmit approved these changes
One nitpick. LGTM otherwise.

/lgtm

2021-03-30 09:55 UTC, dharmit commented on pkg/devfile/adapters/kubernetes/component/adapter.go
> +			return fmt.Errorf("unable to find secret in ServiceBinding %s", link.Name)
```suggestion
			return fmt.Errorf("unable to find secret in ServiceBinding %q", link.Name)
```
In an attempt to make odo errors more readable on the CLI.

2021-03-30 12:28 UTC, merged