WIP: Cleanup context in devfile integration tests
openshift/odo pull request #4564
Opened 2021-03-30 07:42 UTC by valaparthvi

**What type of PR is this?**
> /kind cleanup
**What does does this PR do / why we need it**:
This PR cleans up code that renders the use of `--context` useless.

**Which issue(s) this PR fixes**:

Fixes #3801

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
Run the tests fixed by the PR.

2021-03-30 11:16 UTC, rnapoles-rh commented
PSI tests are optional at this time

2021-03-30 11:24 UTC, rnapoles-rh approved these changes
/lgtm

2021-03-30 12:15 UTC, girishramnani commented
why lgtm a WIP PR @rnapoles-rh ?

2021-03-31 02:37 UTC, rnapoles-rh commented
> why lgtm a WIP PR @rnapoles-rh ?

sorry, I missed the tag

2021-04-05 13:28 UTC, dharmit requested changes

2021-04-05 13:28 UTC, dharmit commented on tests/integration/devfile/cmd_devfile_describe_test.go
> +			// odo delete requires changing directory because it does not work as intended with --context
Can you please make this a TODO and add the issue(s) information?

2021-04-05 13:34 UTC, dharmit commented
@valaparthvi i see a bunch of integration test failures. It's a mess to read through them since the logs are garbled. Can you please take a look if these failures are relevant to the changes you've made in this PR? If not relevant, I think you could trigger a retest.

2021-04-05 14:22 UTC, valaparthvi commented
Those failures are related to my changes, I am still working on them. Sorry, I should've put it back to WIP.

2021-04-06 04:05 UTC, dharmit commented
> Those failures are related to my changes, I am still working on them. Sorry, I should've put it back to WIP.

Np. You don't really need to put it back to WIP when CI helps you discover that some changes need to be made. I generally put a PR in WIP when I know there's some work pending from my side and I don't want the team to waste time reviewing the PR. YMMV. :)

2021-04-06 07:06 UTC, valaparthvi commented
/test unit
/test v4.7-integration-e2e

2021-04-07 05:13 UTC, valaparthvi commented
/test v4.7-integration-e2e

> INFO[2021-04-06T14:17:22Z] • Failure [69.413 seconds]      
INFO[2021-04-06T14:17:22Z] odo devfile push command tests               
INFO[2021-04-06T14:17:22Z] /go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_push_test.go:20 
INFO[2021-04-06T14:17:22Z]   Verify devfile push works                  
INFO[2021-04-06T14:17:22Z]   /go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_push_test.go:64 
INFO[2021-04-06T14:17:22Z]     should execute the default build and run command groups if present [It] 
INFO[2021-04-06T14:17:22Z]     /go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_push_test.go:345 
INFO[2021-04-06T14:17:22Z]                                              
INFO[2021-04-06T14:17:22Z]     Unexpected error:                   
INFO[2021-04-06T14:17:22Z]         <*errors.errorString | 0xc0004281b0>: { 
INFO[2021-04-06T14:17:22Z]             s: "cmd [ps -ef] failed with error Signal 23 (URG) caught by ps (3.3.15).\nps:ps/display.c:66: please report this bug\ncommand terminated with exit code 1\n on pod jivyym-744c4797df-2nv7n", 
INFO[2021-04-06T14:17:22Z]         }                                    
INFO[2021-04-06T14:17:22Z]         cmd [ps -ef] failed with error Signal 23 (URG) caught by ps (3.3.15). 
INFO[2021-04-06T14:17:22Z]         ps:ps/display.c:66: please report this bug 
INFO[2021-04-06T14:17:22Z]         command terminated with exit code 1  
INFO[2021-04-06T14:17:22Z]          on pod jivyym-744c4797df-2nv7n      
INFO[2021-04-06T14:17:22Z]     occurred                             
INFO[2021-04-06T14:17:22Z]                                              
INFO[2021-04-06T14:17:22Z]     /go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_push_test.go:364

Retesting. Although, the failure is unrelated to the changes made by this PR.

2021-04-07 07:11 UTC, valaparthvi commented
/test v4.7-integration-e2e

Retesting, because not all tests were run.

2021-04-07 10:09 UTC, valaparthvi commented
@rnapoles-rh it's now RFR.

2021-04-09 13:59 UTC, rnapoles-rh approved these changes
Nice cleanup
/lgtm

2021-04-12 03:27 UTC, dharmit commented on .github/PULL_REQUEST_TEMPLATE.md
> +**What does this PR do / why we need it**:
Thanks for fixing this! 👍🏾

2021-04-12 03:29 UTC, dharmit reviewed
/approve

2021-04-12 06:14 UTC, merged