Add make help
openshift/odo pull request #4695
Opened 2021-05-05 14:32 UTC by feloy

**What type of PR is this?**

/kind documentation
[skip ci]

**What does this PR do / why we need it**:

Add a `make help` command, extracting comments from Makefile (inspired by https://github.com/kubernetes/website/blob/master/Makefile)

**Which issue(s) this PR fixes**:

N/A

2021-05-05 16:58 UTC, feloy commented
/retest

2021-05-05 19:10 UTC, feloy commented
/retest

2021-05-06 06:54 UTC, dharmit requested changes
Mostly nitpicks in my review.

2021-05-06 06:54 UTC, dharmit commented on Makefile
> +goget-tools: goget-ginkgo ## install tools used for building, tests and  validations
nitpick - an extra space.
```suggestion
goget-tools: goget-ginkgo ## install tools used for building, tests and validations
```

2021-05-06 06:54 UTC, dharmit commented on Makefile
> +test-integration-service-catalog: ## Run command's integration tests which are depend on service catalog enabled cluster.
Nitpick again.
```suggestion
test-integration-service-catalog: ## Run command's integration tests which are dependent on service catalog enabled cluster.
```

2021-05-06 06:54 UTC, dharmit commented on Makefile
> +upload-packages: ## upload packages greated by 'make packages' to bintray repositories
```suggestion
upload-packages: ## upload packages created by 'make packages' to bintray repositories
```

2021-05-06 06:59 UTC, kadel commented
/approve

2021-05-06 07:19 UTC, feloy commented
Thanks @dharmit for the fixes

2021-05-06 08:29 UTC, dharmit approved these changes

2021-05-06 09:50 UTC, feloy commented
/retest

2021-05-06 10:44 UTC, merged