odo catalog describe service <operator> --example
openshift/odo pull request #4821
Opened 2021-06-16 22:26 UTC by girishramnani

**What type of PR is this?**
/kind feature
**What does this PR do / why we need it**:
see $SUBJECT

**Which issue(s) this PR fixes**:

Fixes https://github.com/openshift/odo/issues/4796

**PR acceptance criteria**:

- [ ] Unit test 

- [X] Integration test 

- [ ] Documentation 

- [ ] Update changelog

- [X] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
Install an operator of your liking

```
odo catalog describe service postgresql-operator.v0.1.1/Database --example
apiVersion: postgresql.dev4devs.com/v1alpha1
kind: Database
metadata:
  name: database
spec:
  databaseCpu: 30m
  databaseCpuLimit: 60m
  databaseMemoryLimit: 512Mi
  databaseMemoryRequest: 128Mi
  databaseName: example
  databaseNameKeyEnvVar: POSTGRESQL_DATABASE
  databasePassword: postgres
  databasePasswordKeyEnvVar: POSTGRESQL_PASSWORD
  databaseStorageRequest: 1Gi
  databaseUser: postgres
  databaseUserKeyEnvVar: POSTGRESQL_USER
  image: centos/postgresql-96-centos7
  size: 1
```

2021-06-16 22:44 UTC, girishramnani commented
Will update AC in a subsiquent PR

2021-06-16 22:52 UTC, girishramnani commented
```
odo catalog describe service etcdoperator.v0.9.4-clusterwide/EtcdCluster --example
apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdCluster
metadata:
  annotations:
    etcd.database.coreos.com/scope: clusterwide
  name: example
spec:
  size: 3
  version: 3.2.13

 % odo catalog describe service etcdoperator.v0.9.4-clusterwide/EtcdCluster --example -o json
{
  "apiVersion": "etcd.database.coreos.com/v1beta2",
  "kind": "EtcdCluster",
  "metadata": {
    "annotations": {
      "etcd.database.coreos.com/scope": "clusterwide"
    },
    "name": "example"
  },
  "spec": {
    "size": 3,
    "version": "3.2.13"
  }
}
```

2021-06-17 06:29 UTC, dharmit commented
>      % odo catalog describe service etcdoperator.v0.9.4-clusterwide/EtcdCluster --example -o json
>     {
>       "apiVersion": "etcd.database.coreos.com/v1beta2",
>       "kind": "EtcdCluster",
>       "metadata": {
>         "annotations": {
>           "etcd.database.coreos.com/scope": "clusterwide"
>         },
>         "name": "example"
>       },
>       "spec": {
>         "size": 3,
>         "version": "3.2.13"
>       }
>     }

@girishramnani I don't think this is the way we output JSON data for any command. Why are we deviating in this case?

2021-06-17 06:30 UTC, dharmit commented
> Will update AC in a subsiquent PR - to avoid any unnecessary rebasing

Which acceptance criteria are you referring to?

2021-06-17 06:33 UTC, dharmit requested changes
We need to make changes to the tests to adhere to the flow proposed in #4770. Please change the tests accordingly for this PR.

2021-06-17 07:03 UTC, girishramnani commented
> > Will update AC in a subsiquent PR - to avoid any unnecessary rebasing
> 
> Which acceptance criteria are you referring to?

sorry my mistake `wil update changelog`

2021-06-17 07:05 UTC, girishramnani commented
> We need to make changes to the tests to adhere to the flow proposed in #4770. Please change the tests accordingly for this PR.

I feel its adhere to the flow, there is a before each already which runs the common part and I am just executing the "non-common" part of test in that `It` block.

2021-06-17 07:07 UTC, girishramnani commented
> > ```
> >  % odo catalog describe service etcdoperator.v0.9.4-clusterwide/EtcdCluster --example -o json
> > {
> >   "apiVersion": "etcd.database.coreos.com/v1beta2",
> >   "kind": "EtcdCluster",
> >   "metadata": {
> >     "annotations": {
> >       "etcd.database.coreos.com/scope": "clusterwide"
> >     },
> >     "name": "example"
> >   },
> >   "spec": {
> >     "size": 3,
> >     "version": "3.2.13"
> >   }
> > }
> > ```
> 
> @girishramnani I don't think this is the way we output JSON data for any command. Why are we deviating in this case?

Could you elaborate?

2021-06-17 07:38 UTC, dharmit commented
> > We need to make changes to the tests to adhere to the flow proposed in #4770. Please change the tests accordingly for this PR.
> 
> I feel its adhere to the flow, there is a before each already which runs the common part and I am just executing the "non-common" part of test in that `It` block.

And what about the rest of the test file? Is that file entirely adhering to that flow? If yes, can you update issue #4741 that this file doesn't need any changes to adhere to that flow?

The point is that it's not just about new tests being added to odo repo. We need to modify/refactor existing tests as well if we want the entire integration test suite to look like #4770.

2021-06-17 07:42 UTC, dharmit commented
> Could you elaborate?

We're missing the GVKR info for JSON output.

If you do `odo catalog describe service <operator>/<cr> -o json`, you see ouptut like:
```json
{
        "kind": "CRDDescription",
        "apiVersion": "odo.dev/v1alpha1",
        "metadata": {
                "creationTimestamp": null
        },
        "spec": {}
}
```
What's proposed in this output is only JSON output of the ALM example. So it's more we're only showing the `spec` part.

2021-06-17 08:10 UTC, prietyc123 commented
/test psi-unit-test-mac

2021-06-17 08:10 UTC, dharmit commented
> > 
> 
> And what about the rest of the test file? Is that file entirely adhering to that flow? If yes, can you update issue #4741 that this file doesn't need any changes to adhere to that flow?
> 
> The point is that it's not just about new tests being added to odo repo. We need to modify/refactor existing tests as well if we want the entire integration test suite to look like #4770.

My bad on this one. I didn't notice that this was the same file as other OperatorHub tests. Sorry about the confusion.

2021-06-17 08:47 UTC, mik-dass commented on pkg/odo/cli/catalog/describe/service.go
> +	IsExample bool
This can be a non exported

2021-06-17 08:49 UTC, girishramnani commented on pkg/odo/cli/catalog/describe/service.go
> +	IsExample bool
agreed, will change

2021-06-17 10:21 UTC, girishramnani commented
this is how it looks like now 
```
{
  "kind": "OperatorExample",
  "apiVersion": "odo.dev/v1alpha1",
  "metadata": {
    "creationTimestamp": null
  },
  "spec": {
    "apiVersion": "etcd.database.coreos.com/v1beta2",
    "kind": "EtcdCluster",
    "metadata": {
      "annotations": {
        "etcd.database.coreos.com/scope": "clusterwide"
      },
      "name": "example"
    },
    "spec": {
      "size": 3,
      "version": "3.2.13"
    }
  }
}
```

2021-06-17 10:22 UTC, girishramnani commented
human readable version looks like 
```
odo catalog describe service etcdoperator.v0.9.4-clusterwide/EtcdCluster --example        apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdCluster
metadata:
  annotations:
    etcd.database.coreos.com/scope: clusterwide
  name: example
spec:
  size: 3
  version: 3.2.13
```

2021-06-17 10:23 UTC, girishramnani commented on pkg/odo/cli/catalog/describe/service.go
> +	IsExample bool
done, addressed the comment

2021-06-17 10:31 UTC, dharmit commented
> this is how it looks like now
> 
> ```
> {
>   "kind": "OperatorExample",
>   "apiVersion": "odo.dev/v1alpha1",
>   "metadata": {
>     "creationTimestamp": null
>   },
>   "spec": {
>     "apiVersion": "etcd.database.coreos.com/v1beta2",
>     "kind": "EtcdCluster",
>     "metadata": {
>       "annotations": {
>         "etcd.database.coreos.com/scope": "clusterwide"
>       },
>       "name": "example"
>     },
>     "spec": {
>       "size": 3,
>       "version": "3.2.13"
>     }
>   }
> }
> ```

Thanks @girishramnani for this. When I looked at the output, it got me wondering if we should have a key in the `spec:` and put the alm example as its value. Something like:
```json
{
  "kind": "OperatorExample",
  "apiVersion": "odo.dev/v1alpha1",
  "metadata": {
    "creationTimestamp": null
  },
  "spec": {
    someKey: {
    "apiVersion": "etcd.database.coreos.com/v1beta2",
    "kind": "EtcdCluster",
    "metadata": {
      "annotations": {
        "etcd.database.coreos.com/scope": "clusterwide"
      },
      "name": "example"
    },
    "spec": {
      "size": 3,
      "version": "3.2.13"
    }
  }
}}

```

@kadel do you have any suggestion on this?

@girishramnani Sorry about being a pain on this PR.

2021-06-17 10:39 UTC, girishramnani commented on pkg/odo/cli/catalog/describe/service.go
> +	IsExample bool
done

2021-06-17 10:40 UTC, girishramnani commented
what should be the `somekey` though?

2021-06-17 12:29 UTC, girishramnani commented
```
msg=Error: error creating Route53 Hosted Zone: TooManyHostedZones: Limits Exceeded: MAX_HOSTED_ZONES_BY_OWNER - Cannot create more hosted zones.
level=error msg=	status code: 400, request id: eabc56f1-58a7-4312-ab01-cd808a9fcaff
```

2021-06-17 12:29 UTC, girishramnani commented
/retest

2021-06-18 06:30 UTC, girishramnani commented
```
level=error
46
level=error msg=Error: [ERR]: Error building changeset: InvalidChangeBatch: [Tried to create resource record set [name='api.ci-op-kxqb4brl-89922.origin-ci-int-aws.dev.rhcloud.com.', type='A'] but it already exists]
```

2021-06-18 06:30 UTC, girishramnani commented
/retest

2021-06-18 15:06 UTC, feloy commented
/lgtm

As a user, it seems strange to me that the JSON content is not the same as the YAML one (but encapsulates the contents into an `OperatorExample` resource), but I understand we have to stick to the general JSON format

2021-06-21 11:53 UTC, kadel commented
> Thanks @girishramnani for this. When I looked at the output, it got me wondering if we should have a key in the `spec:` and put the alm example as its value. Something like:

I think that the current format makes sense (no extra keys in `spec`)

2021-06-21 13:20 UTC, girishramnani commented
Ack. Thank you.
Could you please take a look @dharmit

2021-06-22 11:14 UTC, dharmit commented
> As a user, it seems strange to me that the JSON content is not the same as the YAML one (but encapsulates the contents into an `OperatorExample` resource), but I understand we have to stick to the general JSON format

Yeah. I agree on this one. But at the same time, I'm not sure if we should make an exception here because it's using the same flag (`-o json`) that's used elsewhere for JSON output.

/approve

2021-06-22 13:12 UTC, merged