Adds a column in odo list output to indicate components created by odo
openshift/odo pull request #4962
Opened 2021-08-02 12:34 UTC by mik-dass

**What type of PR is this?**

/kind feature

**What does this PR do / why we need it**:

It adds a column in odo list output to indicate which components are created by odo.

**Which issue(s) this PR fixes**:

Fixes #4808

**PR acceptance criteria**:

- [ ] Unit test 

- [X] Integration test 

- [ ] Documentation 

- [ ] Update changelog

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

- Deploy some components in the same and different apps.
- `odo list`, `odo list --app <app-name>` && `odo list --all-apps` should display a column indicating which components are managed by odo.

Example output:
```
$ odo list --all-apps 
APP         NAME                         PROJECT     TYPE       STATE      MANAGED BY ODO
new-app     nodejs-nodejs-basic-ummk     blah        nodejs     Pushed     No
```

2021-08-03 08:30 UTC, mik-dass commented
```
[odo]  ✗  Failed to start component with name "nodejs". Error: Failed to create the component: error while waiting for deployment rollout: timeout while waiting for nodejs-app deployment roll out\nFor more information to help determine the cause of the error, re-run with '-v'.
[odo] See below for a list of failed events that occured more than 5 times during deployment:
[odo] 
[odo]  NAME                                          COUNT  REASON  MESSAGE                 
[odo] 
[odo]  nodejs-app-6ffdbcc54d-qwnj6.1697bb4dc6bdbcf3  5      Failed  Error: ImagePullBackOff 
```
/retest

2021-08-04 06:56 UTC, dharmit approved these changes
/lgtm
/approve

adding both since it isn't a big change and I looked at both functionality as well as code.

2021-08-04 08:23 UTC, dharmit requested changes
Please update the Changelog.md file.

2021-08-05 06:45 UTC, mik-dass commented
> Please update the Changelog.md file.

Updated

2021-08-05 06:48 UTC, dharmit approved these changes

2021-08-05 08:40 UTC, merged