add tests for .devfile.yaml support
openshift/odo pull request #5216
Opened 2021-11-08 17:58 UTC by anandrkskd

Signed-off-by: anandrkskd <anandrkskd@gmail.com>

**What type of PR is this?**
 /kind tests

**What does this PR do / why we need it**:
Add tests for `.devfile.yaml` support
**Which issue(s) this PR fixes**: 

Fixes https://github.com/openshift/odo/issues/5167

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

2021-11-09 05:55 UTC, anandrkskd commented
/test psi-unit-test-windows

2021-11-09 14:03 UTC, feloy requested changes

2021-11-10 07:50 UTC, anandrkskd commented on tests/integration/devfile/cmd_dot_devfile_test.go
> +	Context("Operators are installed in the cluster", func() {
I think we can remove the above test of `odo service`  and replace it with this one, as it's also testing the `service create` for us in a way.

2021-11-10 07:53 UTC, anandrkskd commented on tests/integration/devfile/cmd_dot_devfile_test.go
> +			helper.CopyExampleDevFile(filepath.Join("source", "devfiles", "nodejs", "devfile.yaml"), filepath.Join(commonVar.Context, ".devfile.yaml"))
But is it not the devfile that we are using for testing, I think it's better to use the devfile we have on our example, and if I remember correctly we faced protocol error some time before.

2021-11-10 11:24 UTC, anandrkskd commented on tests/integration/devfile/cmd_dot_devfile_test.go
> +	Context("Operators are installed in the cluster", func() {
As discussed in the call we want to merge but the devfile we are using for this test is different then the devfile that we are using in the test in the starting of the file. I think we can use this context and move the test which is in the starting of file to this context

2021-11-12 07:17 UTC, feloy requested changes

2021-11-12 07:17 UTC, feloy commented on tests/integration/devfile/cmd_dot_devfile_test.go
> +		When("should list the storage with the proper states and container names", func() {
```suggestion
		When("creating a storage", func() {
```

2021-11-12 07:17 UTC, feloy commented on tests/integration/devfile/cmd_dot_devfile_test.go
> +			helper.WaitForCmdOut("odo", odoArgs, 5, true, func(output string) bool {
This operation can be quite long, please place this block in a BeforeEach where it is needed only, and not the more englobing one (in `When("Creating a nodejs component and replace devfile.yaml with .devfile.yaml"` I think).

2021-11-15 04:23 UTC, anandrkskd commented
/retest

2021-11-15 12:01 UTC, feloy commented
/lgtm
/approve

2021-11-15 13:36 UTC, merged