Refactoring cmd_devfile_watch_tests
openshift/odo pull request #5219
Opened 2021-11-09 18:52 UTC by rnapoles-rh

**What type of PR is this?**

> /kind tests

**What does this PR do / why we need it**:
Refactoring cmd_devfile_watch_tests tests 

**Which issue(s) this PR fixes**:

Fixes #5161 

**PR acceptance criteria**:

- [x] Unit test 

- [x] Integration test 

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

2021-11-22 08:04 UTC, feloy commented
/test psi-kubernetes-integration-e2e

```
[ssh:Fedora-32-minikube] [Fail] odo service command tests for OperatorHub Operators are installed in the cluster a specific operator is installed when a nodejs component is created when a Redis instance is created with no name and inlined flag is used when odo push is executed [BeforeEach] when a link is created with the service Should fail to link it again 
[ssh:Fedora-32-minikube] /home/fedora/amqp_ci_rcv_odo-minikube-pr-build_PR_5219/KdBkf/repo/tests/helper/helper_cmd_wrapper.go:100
[ssh:Fedora-32-minikube] 
[ssh:Fedora-32-minikube] [Fail] odo link command tests for OperatorHub Operators are installed in the cluster when a component and a service are deployed when a link between the component and the service is created when odo push is executed [BeforeEach] should find files in component container 
```

2021-11-22 08:29 UTC, feloy requested changes

2021-11-22 08:29 UTC, feloy commented on tests/integration/devfile/cmd_devfile_watch_test.go
> +	When("executing watch without pushing a devfile component", func() {
The `When` contents should explain what is doing the `BeforeEach` part only, here something similar to `When("a component is created"`

2021-11-22 08:29 UTC, feloy commented on tests/integration/devfile/cmd_devfile_watch_test.go
> +		It("should fail", func() {
`should fail when odo push is not executed`?

2021-11-22 08:29 UTC, feloy commented on tests/integration/devfile/cmd_devfile_watch_test.go
> +	When("executing odo watch", func() {
When("a component is created and pushed"

2021-11-23 16:30 UTC, rnapoles-rh commented
Closing as it is replaced with https://github.com/openshift/odo/pull/5244

2021-11-23 16:31 UTC, closed without merging